# .github/workflows/deploy.yml

name: Deploy OSRM API

on:
  push:
    branches:
      - main

jobs:
  osrm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Download PBF file using wget
      run: |
        wget -O south-korea-latest.osm.pbf https://download.geofabrik.de/asia/south-korea-latest.osm.pbf

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Pull OSRM Docker image
      run: docker pull osrm/osrm-backend:latest

    - name: Prepare OSRM data
      run: |
        docker run -t -v $(pwd):/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/south-korea-latest.osm.pbf
        docker run -t -v $(pwd):/data osrm/osrm-backend osrm-partition /data/south-korea-latest.osrm
        docker run -t -v $(pwd):/data osrm/osrm-backend osrm-customize /data/south-korea-latest.osrm

    - name: Start OSRM Routing Server
      run: |
        docker run -d -t -i -p 5000:5000 -v $(pwd):/data osrm/osrm-backend osrm-routed --algorithm mld /data/south-korea-latest.osrm
